### ISSUE TITLE
This example does not seem to work on mono 3.12.0

### ISSUE THREAD

**Issue by smnbss** [badjer/asp5-mac-demo#1]
I've got this error when running it on osx

kpm --version
1.0.0-beta3-11030
osx
10.10.2
mono -V
Mono JIT compiler version 3.12.0 (tarball Wed Jan 28 15:32:29 GMT 2015)

```
asp5-mac-demo simone$ k kestrel
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Framework.ConfigurationModel.IConfiguration, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Microsoft.Framework.ConfigurationModel.IConfiguration, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
```

**Comment by badjer** [comment]
Hmm, yeah. It looks like the ASP Net team just released a new version of the framework. I had been running this on the beta-2 release.

I suspect this _should_ be fixable by downgrading the kre version, something like: 

```
kvm install 1.0.0-beta-2
kvm use 1.0.0-beta2
```

But I can't find the correct version number for that version of kre anymore. 

The project file is generated from the Yeoman ASP Net generator here: https://github.com/OmniSharp/generator-aspnet  Once they update for beta3, we should be able to use their generated project file to make it work with beta3.

**Comment by badjer** [comment]
Found the solution here: https://github.com/aspnet/Home/issues/310. Basically, it looks like the homebrew package for kvm got updated to beta3 before the nuget repo did. I'll update to generalize the references and explicitly set the nuget source.
